// src/content/ContentGenerator.js
export class ContentGenerator {
  generate(role, taskType, context = {}) {
    const generator = this.#generators[taskType];
    if (!generator) return this.#defaultContent(role, taskType, context);
    return generator(role, context);
  }

  #generators = {
    vision: (role, ctx) => [
      `# Vision Document`,
      ``,
      `## Project: ${ctx.projectName || 'Unnamed'}`,
      ``,
      `### Problem Statement`,
      ctx.problem || '_Define the core problem being solved_',
      ``,
      `### Target Audience`,
      ctx.audience || '_Identify primary users_',
      ``,
      `### Solution Overview`,
      ctx.solution || '_Describe the proposed solution_',
      ``,
      `### Key Differentiators`,
      ctx.differentiators || '_What makes this unique_',
      ``,
      `### Success Metrics`,
      ctx.metrics || '_How will success be measured_',
    ].join('\n'),

    strategy: (role, ctx) => [
      `# Strategic Plan`,
      ``,
      `## Phase 1: Foundation (Weeks 1-4)`,
      ctx.phase1 || '_Core product development_',
      ``,
      `## Phase 2: Growth (Weeks 5-8)`,
      ctx.phase2 || '_User acquisition and iteration_',
      ``,
      `## Phase 3: Scale (Weeks 9-12)`,
      ctx.phase3 || '_Scaling operations_',
    ].join('\n'),

    'market-analysis': (role, ctx) => [
      `# Market Analysis`,
      ``,
      `## Market Size`,
      ctx.marketSize || '_TAM/SAM/SOM analysis_',
      ``,
      `## Competitors`,
      ctx.competitors || '_Competitive landscape_',
      ``,
      `## Positioning`,
      ctx.positioning || '_Market positioning strategy_',
    ].join('\n'),

    'technical-spec': (role, ctx) => [
      `# Technical Specification`,
      ``,
      `## Architecture`,
      ctx.architecture || '_System architecture overview_',
      ``,
      `## Tech Stack`,
      ctx.techStack || '_Technology choices and rationale_',
      ``,
      `## API Design`,
      ctx.api || '_API endpoints and contracts_',
      ``,
      `## Data Model`,
      ctx.dataModel || '_Database schema and relationships_',
    ].join('\n'),

    'financial-plan': (role, ctx) => [
      `# Financial Plan`,
      ``,
      `## Revenue Model`,
      ctx.revenue || '_Revenue streams_',
      ``,
      `## Cost Structure`,
      ctx.costs || '_Operating costs_',
      ``,
      `## Projections`,
      ctx.projections || '_Financial projections_',
    ].join('\n'),
  };

  #defaultContent(role, taskType, ctx) {
    return [
      `# ${taskType.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}`,
      ``,
      `_Generated by ${role}_`,
      ``,
      `## Overview`,
      ctx.overview || '_Content to be developed_',
      ``,
      `## Details`,
      ctx.details || '_Details pending_',
    ].join('\n');
  }
}
